---
collections:
  # Export side (AWX /api/v2/)
  - name: awx.awx
  - name: infra.controller_configuration

  # Import side (AAP 2.5+ gateway)
  - name: ansible.controller
  - name: ansible.platform
  - name: infra.aap_configuration
  - name: infra.aap_configuration_extended

  # Utilities
  - name: infra.aap_utilities
  - name: infra.ee_utilities
...
